//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BioskopData
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ADONETBioskopContainer : DbContext
    {
        public ADONETBioskopContainer()
            : base("name=ADONETBioskopContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Film> Films { get; set; }
        public virtual DbSet<Sala> Salas { get; set; }
        public virtual DbSet<Karta> Kartas { get; set; }
        public virtual DbSet<Radnik> Radniks { get; set; }
        public virtual DbSet<Projektor> Projektors { get; set; }
        public virtual DbSet<Kupac> Kupacs { get; set; }
        public virtual DbSet<Projekcija> Projekcijas { get; set; }
        public virtual DbSet<Odrzava> Odrzavas { get; set; }
        public virtual DbSet<Osposobljen> Osposobljens { get; set; }
    }
}
