//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BioskopData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Osposobljen
    {
        public int  ProjektantJMBG { get; set; }
        public int ProjektorId { get; set; }
    
        public virtual Projektant Projektant { get; set; }
        public virtual Projektor Projektor { get; set; }
    }
}
