//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BioskopData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Projektor
    {
        public int Id { get; set; }
        public string Model { get; set; }
        public int Cena { get; set; }
    
        public virtual Sala Sala { get; set; }
    }
}
