//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BioskopData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Projekcija
    {
        public int Id { get; set; }
        public System.DateTime Pocetak { get; set; }
        public System.DateTime Kraj { get; set; }
        public int FilmId { get; set; }
        public int SalaBroj { get; set; }
    
        public virtual Film Film { get; set; }
        public virtual Sala Sala { get; set; }
    }
}
